### ISSUE TITLE
[0.5pt] Add header - group task

### ISSUE THREAD

**Issue by oovillagran** [oovillagran/Capstone-Module2#17]
Create page header according to the wireframe:

<img width="541" alt="Screenshot 2021-06-27 at 21 42 24" src="https://user-images.githubusercontent.com/7466903/123557332-ac3eee80-d790-11eb-91c8-9f8a6a38a4ff.png">

**Comment by naanmohammed** [comment]
#23

**Comment by naanmohammed** [comment]
TMDB Movies API was used.

**Comment by oovillagran** [comment]
Hi Naan, this is the PR for this activity:
https://github.com/oovillagran/Capstone-Module2/pull/23
